# Generated by Django 5.0.3 on 2024-03-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTurno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=5000)),
                ('icon', models.TextField(max_length=5000)),
            ],
        ),
    ]
