# Generated by Django 5.0.3 on 2024-03-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_asesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.TextField(max_length=5000)),
                ('nombre', models.TextField(max_length=1000)),
            ],
        ),
    ]
