# Generated by Django 5.0.3 on 2024-03-20 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_estadoturno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consecutivo', models.TextField(max_length=5000)),
                ('fecha_hora_solicitud', models.DateTimeField(null=True)),
                ('fecha_hora_atencion_turno', models.DateTimeField(null=True)),
                ('fecha_hora_finalizacion_turno', models.DateTimeField(null=True)),
                ('id_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos.categoriaturno')),
                ('id_estado_turno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos.estadoturno')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos.usuario')),
            ],
        ),
    ]
